Task-47220: Inconsistence of WYSIWYG in Table display
Meeds-io/notes pull request #148
Opened 2021-07-29 10:51 UTC by lbengayed

2021-07-30 09:15 UTC, ahamdi requested changes
Please add a description for this PR

2021-07-30 09:15 UTC, ahamdi commented on notes-service/src/main/resources/locale/portlet/Portlets_en.properties
> +SpaceSettings.application.notes.application.title=Notes Application
this file should be removed

2021-07-30 09:15 UTC, ahamdi commented on notes-webapp/src/main/webapp/skin/less/notes/notes.less
> +	overflow: auto;
Fix indentation of this file

2021-07-30 09:15 UTC, ahamdi commented on notes-webapp/src/main/webapp/skin/less/notes/notes.less
> +	  border-right: none;
Consider RTLisation please

2021-07-30 09:15 UTC, ahamdi commented on notes-webapp/src/main/webapp/skin/less/notes/notes.less
> +		  border-right: 1px solid var(--allPagesBorderColor,#e1e8ee);
Consider RTLisation please

2021-08-13 07:03 UTC, rdenarie requested changes
Hello,
Can you add a description following [our commit message best practises](https://developer.exoplatform.org/#id-commits-messages-best-practices)
It help us to understand what you want to do

2021-08-17 06:37 UTC, rdenarie approved these changes

2021-08-17 12:57 UTC, ahamdi approved these changes

2021-08-17 13:44 UTC, merged