Improve export
Meeds-io/notes pull request #520
Opened 2022-05-10 09:25 UTC by mkrout

2022-05-10 11:28 UTC, plamarque commented on notes-service/src/main/java/org/exoplatform/wiki/service/ExportAction.java
> + * Copyright (C) 2022 eXo Platform SAS
copyright meeds / LGPL license

2022-05-10 11:30 UTC, plamarque commented on notes-service/src/test/java/org/exoplatform/wiki/service/TestNoteService.java
> +      e.printStackTrace();
log it please

2022-05-10 11:32 UTC, plamarque requested changes
Check all headers. Should be copyright meeds 2022, LGPL

2022-05-10 14:35 UTC, ahamdi submitted a review, later dismissed

2022-05-11 09:43 UTC, lbengayed approved these changes

2022-05-11 09:48 UTC, merged